### ISSUE TITLE
I would like to join your team and contribute with my many years of experience and skills.

### ISSUE THREAD

**Issue by johnsmith0212** [sui-potatoes/app#15]
Hi, I'm Ethan Tan, a seasoned web full-stack and blockchain developer with over 8 years of experience in the industry. I specialize in building robust, scalable web applications and innovative blockchain solutions. Leveraging my expertise in frameworks like React.js, Vue.js, and Next.js, along with my proficiency in Solidity for smart contract development, I deliver high-quality, secure, and efficient solutions tailored to meet your specific needs.

**Comment by damirka** [comment]
Hello sir! We're open to contributions. Feel free to suggest any code changes or other improvements!

**Comment by johnsmith0212** [comment]
I want a full-time developer position.

**Comment by damirka** [comment]
Well, we're a group of individuals doing this completely for free and on our own spare time. So I don't think that works, unfortunately.

**Comment by johnsmith0212** [comment]
okay I see
If you need developer, plz contact me
